FROM ghcr.io/qmk/qmk_base_container:latest

RUN apt update
RUN apt -y install build-essential git avrdude avrdude-doc gcc-avr avr-libc

RUN python3 -m pip uninstall -y qmk || true
RUN python3 -m pip install --upgrade pip setuptools wheel nose2 && \
    python3 -m pip install qmk

RUN qmk setup -y
